#!/bin/bash
echo ""
bin/gn gen out/linux-debug --args='skia_use_gl=true target_os="linux" cc="clang" cxx="clang++"'

ninja -C out/linux-debug  viewer
#ninja -C out/linux-debug  HelloWorldApp

echo ""
echo "Run Test:"
echo "out/linux-debug/viewer"
#echo "out/linux-debug/TemplateApp"
#echo "out/linux-debug/ImageTest"
#echo "out/linux-debug/TouchApp"
#echo "out/linux-debug/EdisonApp"
echo ""

#out/linux-debug/HelloWorldApp
#out/linux-debug/EdisonApp

